import pathlib
import unittest


class ReleasePromotionWorkflowTests(unittest.TestCase):
    def test_workflow_enforces_signed_approval_gate(self):
        repo_root = pathlib.Path(__file__).resolve().parents[1]
        workflow_path = repo_root / ".github" / "workflows" / "release_promotion.yml"
        self.assertTrue(workflow_path.exists(), "release promotion workflow is missing")

        payload = workflow_path.read_text(encoding="utf-8")

        self.assertIn("python ./soenc.py approve-release", payload)
        self.assertIn("python ./soenc.py release", payload)
        self.assertIn("--require-release-approval", payload)
        self.assertIn("python ./soenc.py promotion-dry-run", payload)
        self.assertIn("python ./soenc.py verify-promotion-artifacts", payload)
        self.assertIn("python ./soenc.py bundle-promotion-artifacts", payload)
        self.assertIn("--require-ci-context-match", payload)
        self.assertIn("--require-artifact-context-consistency", payload)
        self.assertIn("--release-approval-key-b64", payload)
        self.assertIn("--release-approval-key-id", payload)
        self.assertIn("--require-release-approval-signature", payload)
        self.assertIn("PROMOTION_REPORT_FILE", payload)
        self.assertIn("SOENC_RELEASE_APPROVAL_KEY_B64", payload)
        self.assertIn("SOENC_RELEASE_APPROVAL_PREVIOUS_KEY_B64", payload)
        self.assertIn("rotation_rehearsal", payload)
        self.assertIn("rotation_report_file", payload)
        self.assertIn("promotion_policy_file", payload)
        self.assertIn("promotion_workflow_file", payload)
        self.assertIn("promotion_artifact_audit_report_file", payload)
        self.assertIn("promotion_run_receipt_file", payload)
        self.assertIn("promotion_artifact_bundle_file", payload)
        self.assertIn("PROMOTION_POLICY_FILE", payload)
        self.assertIn("PROMOTION_WORKFLOW_FILE", payload)
        self.assertIn("PROMOTION_ARTIFACT_AUDIT_REPORT_FILE", payload)
        self.assertIn("PROMOTION_RUN_RECEIPT_FILE", payload)
        self.assertIn("PROMOTION_ARTIFACT_BUNDLE_FILE", payload)
        self.assertIn("ROTATION_REPORT_FILE", payload)
        self.assertIn("enc2sop-rotation-rehearsal/v1", payload)
        self.assertIn("if: ${{ always() }}", payload)
        self.assertIn("promotion_evidence_file", payload)
        self.assertIn("promotion_report_file", payload)
        self.assertIn("GITHUB_TOKEN", payload)
        self.assertIn("SKIP_PROMOTION_COLLECT", payload)
        self.assertIn("Require Protected Ref Context", payload)
        self.assertIn("if [ \"${GITHUB_REF_PROTECTED:-}\" != \"true\" ]; then", payload)
        self.assertIn("Promotion workflow requires protected ref context (GITHUB_REF_PROTECTED=true)", payload)
        self.assertIn("actions: read", payload)
        self.assertIn("soenc-promotion-${{ github.run_id }}-attempt-${{ github.run_attempt }}", payload)
        self.assertIn("release_approval.json", payload)
        self.assertIn("release_receipt.json", payload)
        self.assertIn("promotion_evidence.json", payload)
        self.assertIn("promotion_audit_report.json", payload)
        self.assertIn("promotion_artifact_audit_report.json", payload)
        self.assertIn("rotation_rehearsal_report.json", payload)
        self.assertIn("promotion_run_receipt.json", payload)
        self.assertIn("promotion_artifact_bundle.zip", payload)
        self.assertIn("\"workflow_name\": \"${GITHUB_WORKFLOW}\"", payload)
        self.assertIn("\"workflow_repository\": \"${GITHUB_REPOSITORY}\"", payload)
        self.assertIn("\"workflow_run_number\": \"${GITHUB_RUN_NUMBER}\"", payload)
        self.assertIn("\"workflow_retention_days\": \"${GITHUB_RETENTION_DAYS}\"", payload)
        self.assertIn("\"workflow_github_actions\": \"${GITHUB_ACTIONS}\"", payload)
        self.assertIn("\"workflow_ci\": \"${CI}\"", payload)
        self.assertIn("\"workflow_runner_environment\": \"${RUNNER_ENVIRONMENT}\"", payload)
        self.assertIn("\"workflow_runner_os\": \"${RUNNER_OS}\"", payload)
        self.assertIn("\"workflow_runner_arch\": \"${RUNNER_ARCH}\"", payload)
        self.assertIn("\"workflow_runner_name\": \"${RUNNER_NAME}\"", payload)
        self.assertIn("\"workflow_ref_name\": \"${GITHUB_REF_NAME}\"", payload)
        self.assertIn("\"workflow_ref_type\": \"${GITHUB_REF_TYPE}\"", payload)
        self.assertIn("\"workflow_name_ref\": \"${GITHUB_WORKFLOW_REF}\"", payload)
        self.assertIn("\"workflow_name_sha\": \"${GITHUB_WORKFLOW_SHA}\"", payload)
        self.assertIn("\"workflow_event\": \"${GITHUB_EVENT_NAME}\"", payload)
        self.assertIn("\"workflow_server_url\": \"${GITHUB_SERVER_URL}\"", payload)
        self.assertIn("\"workflow_api_url\": \"${GITHUB_API_URL}\"", payload)
        self.assertIn("\"workflow_graphql_url\": \"${GITHUB_GRAPHQL_URL}\"", payload)
        self.assertIn("\"workflow_job\": \"${GITHUB_JOB}\"", payload)
        self.assertIn("\"workflow_actor\": \"${GITHUB_ACTOR}\"", payload)
        self.assertIn("\"workflow_triggering_actor\": \"${GITHUB_TRIGGERING_ACTOR}\"", payload)
        self.assertIn("\"workflow_actor_id\": \"${GITHUB_ACTOR_ID}\"", payload)
        self.assertIn("\"workflow_repository_id\": \"${GITHUB_REPOSITORY_ID}\"", payload)
        self.assertIn("\"workflow_repository_owner\": \"${GITHUB_REPOSITORY_OWNER}\"", payload)
        self.assertIn("\"workflow_repository_owner_id\": \"${GITHUB_REPOSITORY_OWNER_ID}\"", payload)
        self.assertIn("\"workflow_ref_protected\": \"${GITHUB_REF_PROTECTED}\"", payload)
        self.assertIn("if-no-files-found: error", payload)

    def test_live_promotion_capture_script_contract(self):
        repo_root = pathlib.Path(__file__).resolve().parents[1]
        script_path = repo_root / "scripts" / "github_release_promotion_evidence.sh"
        self.assertTrue(script_path.exists(), "promotion evidence capture script is missing")
        payload = script_path.read_text(encoding="utf-8")

        self.assertIn("gh workflow run", payload)
        self.assertIn("return_run_details", payload)
        self.assertIn("repos/${repo}/actions/workflows/${workflow_encoded}/dispatches", payload)
        self.assertIn("Workflow dispatch API with run details failed; falling back to gh workflow run...", payload)
        self.assertIn("gh run view", payload)
        self.assertIn("gh api \"repos/${REPO}/actions/runs/${run_id}/artifacts?per_page=100&name=${artifact_name}\"", payload)
        self.assertIn("gh api \"repos/${REPO}/actions/artifacts/${artifact_id}/zip\" --method GET --header \"Accept: application/zip\" --output \"$artifact_zip_path\"", payload)
        self.assertIn("--artifact-index-wait-seconds <int>", payload)
        self.assertIn("Timed out waiting for artifact metadata indexing for ${artifact_name}.", payload)
        self.assertIn("Artifact metadata not yet indexed for ${artifact_name}; retrying in ${POLL_INTERVAL_SECONDS}s...", payload)
        self.assertIn("Artifact archive digest mismatch for {0}: expected {1}, got {2}", payload)
        self.assertIn("Artifact archive size mismatch for {0}: expected {1}, got {2}", payload)
        self.assertIn("Artifact archive member path traversal detected: {0}", payload)
        self.assertIn("Artifact archive contains symlink entry: {0}", payload)
        self.assertIn("promotion_artifact_bundle.zip is missing bundle_manifest.json", payload)
        self.assertIn("bundle_manifest schema mismatch: expected enc2sop-promotion-artifact-bundle/v1, got {0}", payload)
        self.assertIn("bundle_manifest missing required entry: {0}", payload)
        self.assertIn("bundle_manifest sha256 mismatch for {0}: expected {1}, got {2}", payload)
        self.assertIn(
            "promotion_artifact_audit_report schema mismatch: expected enc2sop-promotion-artifact-audit/v1, got {0}",
            payload,
        )
        self.assertIn("promotion_artifact_audit_report.passed must be true", payload)
        self.assertIn("promotion_artifact_audit_report.summary.total_failures must be 0", payload)
        self.assertIn(
            "promotion_run_receipt schema mismatch: expected enc2sop-promotion-run-receipt/v1, got {0}",
            payload,
        )
        self.assertIn("promotion_run_receipt.passed must be true", payload)
        self.assertIn("promotion_run_receipt.rotation_pass_required must be boolean", payload)
        self.assertIn("promotion_run_receipt.rotation_pass_required mismatch: expected {0}, got {1}", payload)
        self.assertIn("promotion_run_receipt.artifacts must be a list", payload)
        self.assertIn("promotion_run_receipt.artifacts missing required entry: {0}", payload)
        self.assertIn("promotion_run_receipt.artifacts[{0}].sha256 mismatch: expected {1}, got {2}", payload)
        self.assertIn("promotion_run_receipt.promotion_artifact_audit_report_file is required", payload)
        self.assertIn(
            "promotion_run_receipt.promotion_artifact_audit_report_file does not match artifacts[promotion_artifact_audit_report].path",
            payload,
        )
        self.assertIn("promotion_run_receipt.github_context missing required key: {0}", payload)
        self.assertIn("promotion_run_receipt.github_context.{0} mismatch: expected {1}, got {2}", payload)
        self.assertIn("Verifying artifact archive digest and extracting ${artifact_name}", payload)
        self.assertIn("soenc-promotion-${run_id}-attempt-${run_attempt}", payload)
        self.assertIn("--run-id <id>", payload)
        self.assertIn("--run-attempt <int>", payload)
        self.assertIn("capture_mode", payload)
        self.assertIn("Using existing workflow run run_id=${run_id} on ${REPO}", payload)
        self.assertIn("run_id_resolution_mode=${run_id_resolution_mode}", payload)
        self.assertIn("\"workflow_run_id_resolution_mode\": run_id_resolution_mode", payload)
        self.assertIn("Dispatch output did not include a run id; resolving via recent workflow runs...", payload)
        self.assertIn("--run-attempt requires --run-id.", payload)
        self.assertIn("run_attempt mismatch for run_id=${run_id}", payload)
        self.assertIn("gh api \"repos/${REPO}/actions/runs/${run_id}\"", payload)
        self.assertIn("Artifact list payload is invalid for run metadata verification.", payload)
        self.assertIn("Expected exactly one artifact named {0}; found {1}.", payload)
        self.assertIn("Artifact workflow_run.id mismatch for {0}: expected {1}, got {2}", payload)
        self.assertIn("Artifact {0} has invalid digest metadata.", payload)
        self.assertIn("run event mismatch between summary and run details for run_id=${run_id}", payload)
        self.assertIn("head_branch mismatch between summary and run details for run_id=${run_id}", payload)
        self.assertIn("artifact workflow_head_branch mismatch for run_id=${run_id}", payload)
        self.assertIn("artifact workflow_head_sha mismatch for run_id=${run_id}", payload)
        self.assertIn("workflow path mismatch for run_id=${run_id}", payload)
        self.assertIn("run event mismatch for dispatched run_id=${run_id}", payload)
        self.assertIn("run event is not supported for promotion evidence capture", payload)
        self.assertIn("head_branch mismatch for run_id=${run_id}", payload)
        self.assertIn("workflow_path", payload)
        self.assertIn("workflow_path_ref", payload)
        self.assertIn("workflow_head_branch", payload)
        self.assertIn("workflow_head_sha", payload)
        self.assertIn("workflow_run_number", payload)
        self.assertIn("artifact_metadata", payload)
        self.assertIn("artifact_archive_verification", payload)
        self.assertIn("digest_verified", payload)
        self.assertIn("size_in_bytes_verified", payload)
        self.assertIn("entry_count_verified", payload)
        self.assertIn("bundle_manifest_verification", payload)
        self.assertIn("required_entries_verified", payload)
        self.assertIn("manifest_sha256", payload)
        self.assertIn("promotion_run_receipt_verification", payload)
        self.assertIn("artifact_entries_verified", payload)
        self.assertIn("artifact_entry_count_verified", payload)
        self.assertIn("workflow_run_html_url", payload)
        self.assertIn("rotation_rehearsal", payload)
        self.assertIn("rotation_report_verification", payload)
        self.assertIn("rotation_rehearsal_report.status must be passed when rotation rehearsal is required; got {0}", payload)
        self.assertIn("rotation_rehearsal_report.requested must be true when rotation rehearsal is required", payload)
        self.assertIn("rotation_rehearsal_report.executed must be true when rotation rehearsal is required", payload)
        self.assertIn("rotation_rehearsal_report.old_key_rejected must be true when rotation rehearsal is required", payload)
        self.assertIn("rotation_rehearsal_report.status must be not-requested when rotation rehearsal is not required; got {0}", payload)
        self.assertIn("rotation_rehearsal_report.requested must be false when rotation rehearsal is not required", payload)
        self.assertIn("promotion_capture_receipt.json", payload)
        self.assertIn("\"release_bundle.json\"", payload)
        self.assertIn("\"release_approval.json\"", payload)
        self.assertIn("\"release_receipt.json\"", payload)
        self.assertIn("\"promotion_evidence.json\"", payload)
        self.assertIn("\"promotion_audit_report.json\"", payload)
        self.assertIn("\"rotation_rehearsal_report.json\"", payload)
        self.assertIn("\"promotion_artifact_audit_report.json\"", payload)
        self.assertIn("\"promotion_run_receipt.json\"", payload)
        self.assertIn("\"promotion_artifact_bundle.zip\"", payload)
        self.assertIn("enc2sop-promotion-evidence-capture/v1", payload)


if __name__ == "__main__":
    unittest.main()
